name: discord
on: workflow_dispatch

jobs:
  discord:
    runs-on: ubuntu-latest
    name: Sending to Discord
    steps:
      - name: Get current time
        id: time
        run: echo "current_time=$(date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_OUTPUT"
      - name: Send to Discord
        id: discord-notify
        uses: pahud/discord-notify@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          message: "The current time is ${{ steps.time.outputs.current_time }}"